[package]
name = "as-tree"
version = "0.12.0"
authors = ["Jake Zimmerman <zimmerman.jake@gmail.com>"]
edition = "2018"

[dependencies]
ansi_term = "0.12"
lscolors = "0.7"
atty = "0.2"
argh = "0.1.3"

[dev-dependencies]
pretty_assertions = "0.6.1"

[profile.release]
codegen-units = 1
